model: resnet

population_size: 400
scale_factor: 0.5
num_iterations: 100
num_perturbations: 1

confidence: 0.5
max_proc: 4

input_dir: images/cifar10/test/
output_dir: images/output/
test_output_dir: images/test_dataset/
